title: gabrielpaulos
url: "https://gabrielpaulos.com"
baseurl: /
# Permalink configuration
permalink: /:title/

# Ensure posts are processed
future: true
# Base URL (important if you're hosting on GitHub Pages)
#baseurl: 

# Site URL (if different from baseurl)#
#url: ""


markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Hello there stranger! Welcome to my address on the internet!"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "blog"
   link: "/blog/"
