title = "iván higuera-mendieta"
baseURL = "https://www.ivanhigueram.com"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = true    # enable KaTeX (https://katex.org/) globally

[params]
  author = "Ivan Higuera-Mendieta"
  profilePicture = "/avatar.jpg"
  description = "My place in the interwebs"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "Made with 🧡  and without tracking cooies"
    url = "https://www.eff.org/issues/do-not-track"
    photocreds = "Photo credits to Daisy Lu" 
    urlphoto = "https://daisylu.github.io/"
## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/ivanhigueram/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/ivanhigueram"

[[params.socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://sigmoid.social/@ivanhigueram"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "about"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "contact"
    url = "/contact"
    weight = 2
  [[menu.main]]
    name = "blog"
    url = "https://topcat.prose.sh/"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
